#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "EXTI_config.h"
#include "EXTI_interface.h"
#include "EXTI_private.h"
#include "EXTI_register.h"

void EXTI_voidINT0Init()
{
	#if EXTI_u8_INT0_SENSE_CONTROL == EXTI_u8_SENSE_LOW_LEVEL

	CLR_BIT(MCUCR, MCUCR_ISC00);
	CLR_BIT(MCUCR, MCUCR_ISC01);

	#elif EXTI_u8_INT0_SENSE_CONTROL == EXTI_u8_SENSE_ON_CHANGE

	SET_BIT(MCUCR, MCUCR_ISC00);
	CLR_BIT(MCUCR, MCUCR_ISC01);

	#elif EXTI_u8_INT0_SENSE_CONTROL == EXTI_u8_SENSE_FALLING_EDGE

	CLR_BIT(MCUCR, MCUCR_ISC00);
	SET_BIT(MCUCR, MCUCR_ISC01);

	#elif EXTI_u8_INT0_SENSE_CONTROL == EXTI_u8_SENSE_RISING_EDGE

	SET_BIT(MCUCR, MCUCR_ISC00);
	SET_BIT(MCUCR, MCUCR_ISC01);

	#endif

	SET_BIT(GICR, GICR_INT0);
}

void EXTI_voidINT1Init()
{
	#if EXTI_u8_INT1_SENSE_CONTROL == EXTI_u8_SENSE_LOW_LEVEL

	CLR_BIT(MCUCR, MCUCR_ISC10);
	CLR_BIT(MCUCR, MCUCR_ISC11);

	#elif EXTI_u8_INT1_SENSE_CONTROL == EXTI_u8_SENSE_ON_CHANGE

	SET_BIT(MCUCR, MCUCR_ISC10);
	CLR_BIT(MCUCR, MCUCR_ISC11);

	#elif EXTI_u8_INT1_SENSE_CONTROL == EXTI_u8_SENSE_FALLING_EDGE

	CLR_BIT(MCUCR, MCUCR_ISC10);
	SET_BIT(MCUCR, MCUCR_ISC11);

	#elif EXTI_u8_INT1_SENSE_CONTROL == EXTI_u8_SENSE_RISING_EDGE

	SET_BIT(MCUCR, MCUCR_ISC10);
	SET_BIT(MCUCR, MCUCR_ISC11);

	#endif

	SET_BIT(GICR, GICR_INT1);

}

void EXTI_voidINT2Init()
{
	#if EXTI_u8_INT2_SENSE_CONTROL == EXTI_u8_SENSE_FALLING_EDGE

	CLR_BIT(MCUCSR, MCUCSR_ISC2);

	#elif EXTI_u8_INT2_SENSE_CONTROL == EXTI_u8_SENSE_RISING_EDGE

	SET_BIT(MCUCSR, MCUCSR_ISC2);

	#endif

	SET_BIT(GICR, GICR_INT2);
}

void EXTI_voidSetSenseControl(u8 Copy_u8INT, u8 Copy_u8Sense)
{
	if(EXTI_u8_INT0 == Copy_u8INT)
	{
		switch(Copy_u8Sense)
		{
		case EXTI_u8_SENSE_LOW_LEVEL: 	 CLR_BIT(MCUCR, MCUCR_ISC00); CLR_BIT(MCUCR, MCUCR_ISC01); break;
		case EXTI_u8_SENSE_ON_CHANGE: 	 SET_BIT(MCUCR, MCUCR_ISC00); CLR_BIT(MCUCR, MCUCR_ISC01); break;
		case EXTI_u8_SENSE_FALLING_EDGE: CLR_BIT(MCUCR, MCUCR_ISC00); SET_BIT(MCUCR, MCUCR_ISC01); break;
		case EXTI_u8_SENSE_RISING_EDGE:	 SET_BIT(MCUCR, MCUCR_ISC00); SET_BIT(MCUCR, MCUCR_ISC01); break;
		default: break;
		}
	}
	else if(EXTI_u8_INT1 == Copy_u8INT)
	{
		switch(Copy_u8Sense)
		{
		case EXTI_u8_SENSE_LOW_LEVEL: 	 CLR_BIT(MCUCR, MCUCR_ISC10); CLR_BIT(MCUCR, MCUCR_ISC11); break;
		case EXTI_u8_SENSE_ON_CHANGE: 	 SET_BIT(MCUCR, MCUCR_ISC10); CLR_BIT(MCUCR, MCUCR_ISC11); break;
		case EXTI_u8_SENSE_FALLING_EDGE: CLR_BIT(MCUCR, MCUCR_ISC10); SET_BIT(MCUCR, MCUCR_ISC11); break;
		case EXTI_u8_SENSE_RISING_EDGE:	 SET_BIT(MCUCR, MCUCR_ISC10); SET_BIT(MCUCR, MCUCR_ISC11); break;
		default: break;
		}
	}
	else if(EXTI_u8_INT2 == Copy_u8INT)
	{
		if(EXTI_u8_SENSE_FALLING_EDGE == Copy_u8Sense)
		{
			CLR_BIT(MCUCSR, MCUCSR_ISC2);
		}
		else if(EXTI_u8_SENSE_RISING_EDGE == Copy_u8Sense)
		{
			SET_BIT(MCUCSR, MCUCSR_ISC2);
		}
	}
}

void EXTI_voidEnableINT(u8 Copy_u8INT)
{
	if((5>Copy_u8INT) || (7<Copy_u8INT) )
	{
		return;
	}
	else
	{
		SET_BIT(GICR, Copy_u8INT);
	}
}

void EXTI_voidDisableINT(u8 Copy_u8INT)
{
	if((5>Copy_u8INT) || (7<Copy_u8INT) )
	{
		return;
	}
	else
	{
		CLR_BIT(GICR, Copy_u8INT);
	}
}
