#ifndef EXTI_CONFIG_H_
#define EXTI_CONFIG_H_

#define EXTI_u8_INT0_SENSE_CONTROL			EXTI_u8_SENSE_FALLING_EDGE
#define EXTI_u8_INT1_SENSE_CONTROL			EXTI_u8_SENSE_FALLING_EDGE
#define EXTI_u8_INT2_SENSE_CONTROL			EXTI_u8_SENSE_FALLING_EDGE

#endif
